name: Automated Screenshot
on: [push]

jobs:
  take_screenshot:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Selenium
      run: |
        python -m pip install selenium
    - name: Take Screenshot
      run: |
        from selenium import webdriver
        driver = webdriver.Firefox()
        driver.get("https://www.freepik.com/")
        driver.save_screenshot("screenshot.png")
        driver.quit()
